CREATE OR REPLACE TRIGGER GC.GT_LIPM_1  
-------------
BEFORE INSERT
    ON GC.LOG_INTEGRACAO_PEDIDO_MOS
   FOR EACH ROW
 --
DECLARE
 --
BEGIN
 --
 -- OBJETIVO..: GATILHO DE INCLUSAO E ALTERACAO DA TABELA LOG_INTEGRACAO_PEDIDO_MOS
 -- AUTOR/DATA: BRUNOS_LISA, 27/01/2025
 --

 IF INSERTING
 THEN
   SELECT GC.SQ_LIPM.NEXTVAL
     INTO :NEW.ID_LIPM
     FROM DUAL;
   --
   :NEW.DT_INCL     := SYSDATE;
   :NEW.ID_USR_INCL := USER;
   :NEW.NM_USR_INCL := USER;
 END IF;
END;
/


