CREATE TABLE GC.LOG_INTEGRACAO_PEDIDO_MOS
(
    ID_LIPM NUMBER(15),
    ORDER_MOS VARCHAR2(30),
    ORDER_ID VARCHAR2(30),  
    NR_PV_PVD NUMBER NOT NULL, 
    CD_FIL_PVD NUMBER NOT NULL, 
    DT_EMIS_PVD DATE NOT NULL, 
    JSON_POST CLOB , 
    JSON_RESULT CLOB , 
    ID_USR_INCL VARCHAR2(30), 
    NM_USR_INCL VARCHAR2(30), 
    DT_INCL DATE
)
/
ALTER TABLE GC.LOG_INTEGRACAO_PEDIDO_MOS ADD CONSTRAINT PK_LIPM PRIMARY KEY (ID_LIPM)
/
CREATE INDEX GC.IX_LIPM_01 ON GC.LOG_INTEGRACAO_PEDIDO_MOS (NR_PV_PVD) ONLINE PARALLEL 4 TABLESPACE TS_GC_IDX_SMALL
/
ALTER INDEX GC.IX_LIPM_01 NOPARALLEL
/
CREATE INDEX GC.IX_LIPM_02 ON GC.LOG_INTEGRACAO_PEDIDO_MOS (CD_FIL_PVD) ONLINE PARALLEL 4 TABLESPACE TS_GC_IDX_SMALL
/
ALTER INDEX GC.IX_LIPM_02 NOPARALLEL
/
CREATE INDEX GC.IX_LIPM_03 ON GC.LOG_INTEGRACAO_PEDIDO_MOS (DT_EMIS_PVD) ONLINE PARALLEL 4 TABLESPACE TS_GC_IDX_SMALL
/
ALTER INDEX GC.IX_LIPM_03 NOPARALLEL
/
CREATE INDEX GC.IX_LIPM_04 ON GC.LOG_INTEGRACAO_PEDIDO_MOS (DT_INCL) ONLINE PARALLEL 4 TABLESPACE TS_GC_IDX_SMALL
/
ALTER INDEX GC.IX_LIPM_04 NOPARALLEL
/
GRANT SELECT, INSERT, UPDATE, DELETE ON GC.LOG_INTEGRACAO_PEDIDO_MOS TO OMS_NIFI
/
CREATE SEQUENCE GC.SQ_LIPM
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 999999999999999
    NOMINVALUE
    CYCLE
    NOCACHE
    ORDER
/
GRANT SELECT ON GC.LOG_INTEGRACAO_PEDIDO_MOS TO RL_CONS_GC 
/
CREATE OR REPLACE PUBLIC SYNONYM LIPM FOR GC.LOG_INTEGRACAO_PEDIDO_MOS 
/
CREATE OR REPLACE PUBLIC SYNONYM LOG_INTEGRACAO_PEDIDO_MOS FOR GC.LOG_INTEGRACAO_PEDIDO_MOS
